server:
  port: 8080

jwt:
  public-key-path: classpath:keys/public.pem
  # secret: ${JWT_SECRET}   # secret for signing/verifying tokens

gateway:
  whitelist:
    - /api/v1/auth/register
    - /api/v1/auth/login
    - /api/v1/auth/refresh

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,gateway

spring:
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
