server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/sales-core-db

    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false
