server:
  port: 8761
  
spring:
  cloud:
    discovery:
      enabled: false

eureka:
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}   # Railway service hostname
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
