server:
  port: 8081

spring:
  datasource:
    url: ${MYSQLHOST}               # Railway MySQL host
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false                 # disable SQL logging in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false

jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem
  access-token-expiry-ms: 604800000
  refresh-token-expiry-seconds: 604800000
