server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:3306/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false
jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem
  access-token-expiry-ms: 604800000
  refresh-token-expiry-seconds: 604800000
