
server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
        
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false
