server:
  port: 8083

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false
